#include <stdio.h>
void output_compile_time_options(void)
{
printf(
"        GALSF\n"
"        STELLAR_FEEDBACK\n"
"        PHOTO_IONIZATION\n"
"        OUTPUT_STARFORMATION_INFO\n"
"        JEANS_MASS_THRESHOLD\n"
"        SF_ONLY_IN_CONV_FLOWS\n"
"        SF_INSTANT_CUTOFF\n"
"        DETERMINISTIC_SF\n"
"        OUTPUT_VELGRAD\n"
"        MAGNETIC\n"
"        MHD_B_SET_IN_PARAMS\n"
"        SAMPLE_IMF_FROM_GAS\n"
"        N_STELLAR_MASS=1\n"
"        WSS_CIE_COOL\n"
"        CHEMCOOL\n"
"        CHEMISTRYNETWORK=5\n"
"        G0_VARIABLE\n"
"        NEED_HEALPIX\n"
"        TREE_RAD\n"
"        TREE_RAD_H2\n"
"        TREE_RAD_CO\n"
"        NSIDE=1\n"
"        COOLING\n"
"        COOLING_OPERATOR_SPLIT\n"
"        METALS\n"
"        NO_ISEND_IRECV_IN_DOMAIN\n"
"        HYDRO_MESHLESS_FINITE_MASS\n"
"        MULTIPLEDOMAINS=16\n"
"        OUTPUT_TIMESTEP\n"
"\n");
}
