#define GALSF 
#define STELLAR_FEEDBACK 
#define PHOTO_IONIZATION 
#define OUTPUT_STARFORMATION_INFO 
#define JEANS_MASS_THRESHOLD 
#define SF_ONLY_IN_CONV_FLOWS 
#define SF_INSTANT_CUTOFF 
#define DETERMINISTIC_SF 
#define OUTPUT_VELGRAD 
#define MAGNETIC 
#define MHD_B_SET_IN_PARAMS 
#define SAMPLE_IMF_FROM_GAS 
#define N_STELLAR_MASS 1
#define WSS_CIE_COOL 
#define CHEMCOOL 
#define CHEMISTRYNETWORK 5
#define G0_VARIABLE 
#define NEED_HEALPIX 
#define TREE_RAD 
#define TREE_RAD_H2 
#define TREE_RAD_CO 
#define NSIDE 1
#define COOLING 
#define COOLING_OPERATOR_SPLIT 
#define METALS 
#define NO_ISEND_IRECV_IN_DOMAIN 
#define HYDRO_MESHLESS_FINITE_MASS 
#define MULTIPLEDOMAINS 16
#define OUTPUT_TIMESTEP 
